### ISSUE TITLE
ombi version/support

### ISSUE THREAD

**Issue by TheBoxTrot** [therithwikrayani/plex-cgnot#1]
is there a possibility of having another version of the program or a feature integrated into the program that worked with ombi

**Comment by AvMavs** [comment]
Not yet, since the free version of NGROK offers only one app at a time.

However, we may look into this in the future, but we can't guarantee anything now since we don't have any experience with Ombi either and an Ombi Version will likely need to be built from scratch.

— Plex CGNOT Team
