### ISSUE TITLE
Random error causing Plex server to no longer be reached

### ISSUE THREAD

**Issue by TheBoxTrot** [therithwikrayani/plex-cgnot#2]
t=2021-11-11T11:04:01+0800 lvl=eror msg="session closed, starting reconnect loop" obj=csess id=9f7207902b16 err="read EOF from remote peer"
t=2021-11-11T11:04:05+0800 lvl=eror msg="heartbeat timeout, terminating session" obj=csess id=0381c4a56d58 clientid=42e9db9d62efe5d45454ecc54590463b
t=2021-11-11T11:04:11+0800 lvl=eror msg="failed to reconnect session" obj=csess id=9f7207902b16 err="read tcp 192.168.86.123:55930->54.153.228.243:443: i/o timeout"

**Comment by therithwikrayani** [comment]
Pretty sure that's either an issue with ngrok or with your internet; restart the tunnel and you should be ok. Do tell me if it happens repeatedly.

**Comment by TheBoxTrot** [comment]
Restarting the program does fix it but it happens almost once a day

**Comment by therithwikrayani** [comment]
I'll see what I can do

**Comment by therithwikrayani** [comment]
Made the tunnel refresh every 4 hours; shouldn't be any issues to the media being streamed thanks to plex caching. Should avoid the session closing problem.

**Comment by Icenova20** [comment]
When the ngrok session closes it interrupts the currently running plex streams but only once the client's have used up all of their video stream buffer, for instance when using the Plex android app, I need to restart the plex android app so that it checks for and resolves the new IP that was set as custom URL after a few minutes after the tunnel reconnects.
I changed from 4 to 12 hours to mitigate the issue

**Comment by therithwikrayani** [comment]
Changed tunnel restart time to 12 hours, will work on detecting and avoiding tunnel closure (and/or) detecting time of tunnel collapse and restarting tunnel when that happens.

**Comment by AvMavs** [comment]
Any updates?

**Comment by therithwikrayani** [comment]
@TheBoxTrot any updates? if you do still see the error, could you provide more details?

**Comment by TheBoxTrot** [comment]
issue seems to have been solved or is so irregular its not really a problem anymore

**Comment by AvMavs** [comment]
> issue seems to have been solved or is so irregular its not really a problem anymore

Great to hear!
