### ISSUE TITLE
TCP is not supported by plex as a custom server access URL anymore?

### ISSUE THREAD

**Issue by Icenova20** [therithwikrayani/plex-cgnot#3]
I used your latest update and it updates the custom URL fine and opens the tunnel, but I think the fact that it is tcp is meaning I cannot connect to it anymore? I tried disabling secure connections required to no avail.

Possible I'm missing something but thought I would say something just in case.

My work around was to change:

tunnel = ngrok.connect(PUBLIC_PORT, "tcp")

to

tunnel = ngrok.connect(PUBLIC_PORT, "http", bind_tls=True)

I'm not sure the implications of making this change as I haven't had time to see if there is any playback stability issues or anything like that

**Comment by therithwikrayani** [comment]
Yep my mistake there sorry! I'll get a fix up ASAP.

**Comment by therithwikrayani** [comment]
Fixed! please switch to the latest update!
