### ISSUE TITLE
Plex is reachable outside home network but cannot watch streaming due to slow connection

### ISSUE THREAD

**Issue by lzagu00** [therithwikrayani/plex-cgnot#4]
Plex is reachable outside home network however streaming is very slow even the server has 90mbps LAN connection and streaming outside home network has internet speed of 120mbps.

**Comment by AvMavs** [comment]
What is the bitrate that you are playing your content at?

**Comment by therithwikrayani** [comment]
@lzagu00 any updates? Did you turn off remote access in Plex? Could you give more details on errors if any?

**Comment by lzagu00** [comment]
My apologies for the late response it looks like its a problem on my
counter internet provider.

Everything is working Superb right now thankyou very much for this project!

**Comment by therithwikrayani** [comment]
Awesome, glad cgnot is useful!
